name: CMake build DuTs
on:
  push:
    paths-ignore:
      - "Sim_To_DuT_Interface/**"
defaults:
  run:
    working-directory: ./Dummy_DuT
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install dependencies
        run: sudo apt-get update -qq && sudo apt-get install -yq libasio-dev libssl-dev libcurl4-openssl-dev libzmq3-dev
      - name: Preparation
        run: mkdir build
      - name: CMake Build
        run: cmake -S . -B build
      - name: CMake Make
        run: cmake --build build
      - name: Archive built applications
        uses: actions/upload-artifact@v2
        with:
          name: Binaries
          path: |
            Dummy_DuT/build/Dummy_CAN_DuT/Dummy_CAN_DuT
            Dummy_DuT/build/REST_Dummy_DuT/REST_Dummy_DuT
