name: CMake build interface
on:
  push:
    paths-ignore:
      - "Dummy_DuT/REST_Dummy_DuT"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      #- name: Install dependencies
      #  run: sudo apt-get update && sudo apt-get install -yq {your-dep}
      - name: Preparation
        run: mkdir build
      - name: CMake Build
        run: cmake -S . -B build
      - name: CMake Make
        run: cmake --build build