name: Docker build REST_Dummy_DuT
on:
  push:
    paths:
      - "Dummy_DuT/REST_Dummy_DuT/**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build REST_Dummy_DuT
        run: docker build Dummy_DuT/REST_Dummy_DuT --file Dummy_DuT/REST_Dummy_DuT/Dockerfile --tag rest-dummy-dut:$(git rev-parse --short "$GITHUB_SHA")
      - name: Upload image
        uses: ishworkh/docker-image-artifact-upload@v1
        with:
          image: rest-dummy-dut