name: Generate doxyGen and publish to gh pages
on:
  push:
    branches:
      - main
defaults:
  run:
    working-directory: ./doxygen
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install dependencies
        run: sudo apt-get update -qq && sudo apt-get install -yq graphviz libclang1-10 libclang-cpp1-9
      - name: Install doxygen 1.9.2 # Only 1.8.17 in ubuntu 20.04 repository
        run: wget https://www.doxygen.nl/files/doxygen-1.9.2.linux.bin.tar.gz && tar -xf doxygen-1.9.2.linux.bin.tar.gz && cd doxygen-1.9.2 && sudo make install
      - name: Preparation
        run: mkdir build
      - name: CMake Build
        run: cmake -S . -B build
      - name: CMake Make
        run: cmake --build build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: doxygen/doc_doxygen/html
