name: Generate doxyGen and publish to gh pages
on:
  push:
    branches:
      - main
defaults:
  run:
    working-directory: ./doxygen
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install dependencies
        run: sudo apt-get update -qq && sudo apt-get install -yq doxygen graphviz
      - name: Preparation
        run: mkdir build
      - name: CMake Build
        run: cmake -S . -B build
      - name: CMake Make
        run: cmake --build build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: doxygen/doc_doxygen/html
